// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package zenkocloudserver provides the client and types for making API
// requests to Zenko Cloudserver Client.
//
// See https://docs.aws.amazon.com/goto/WebAPI/s3-2006-03-01 for more information on this service.
//
// See zenkocloudserver package documentation for more information.
// https://docs.aws.amazon.com/sdk-for-go/api/service/zenkocloudserver/
//
// Using the Client
//
// To contact Zenko Cloudserver Client with the SDK use the New function to create
// a new service client. With that client you can make API requests to the service.
// These clients are safe to use concurrently.
//
// See the SDK's documentation for more information on how to use the SDK.
// https://docs.aws.amazon.com/sdk-for-go/api/
//
// See aws.Config documentation for more information on configuring SDK clients.
// https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
//
// See the Zenko Cloudserver Client client ZenkoCloudserver for more
// information on creating client for this service.
// https://docs.aws.amazon.com/sdk-for-go/api/service/zenkocloudserver/#New
package zenkocloudserver
