// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package zenkocloudserveriface provides an interface to enable mocking the Zenko Cloudserver Client service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package zenkocloudserveriface

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/aws-sdk-go/service/zenkocloudserver"
)

// ZenkoCloudserverAPI provides an interface to enable mocking the
// zenkocloudserver.ZenkoCloudserver service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // Zenko Cloudserver Client.
//    func myFunc(svc zenkocloudserveriface.ZenkoCloudserverAPI) bool {
//        // Make svc.AbortMultipartUpload request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := zenkocloudserver.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockZenkoCloudserverClient struct {
//        zenkocloudserveriface.ZenkoCloudserverAPI
//    }
//    func (m *mockZenkoCloudserverClient) AbortMultipartUpload(input *zenkocloudserver.AbortMultipartUploadInput) (*zenkocloudserver.AbortMultipartUploadOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockZenkoCloudserverClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type ZenkoCloudserverAPI interface {
	AbortMultipartUpload(*zenkocloudserver.AbortMultipartUploadInput) (*zenkocloudserver.AbortMultipartUploadOutput, error)
	AbortMultipartUploadWithContext(aws.Context, *zenkocloudserver.AbortMultipartUploadInput, ...request.Option) (*zenkocloudserver.AbortMultipartUploadOutput, error)
	AbortMultipartUploadRequest(*zenkocloudserver.AbortMultipartUploadInput) (*request.Request, *zenkocloudserver.AbortMultipartUploadOutput)

	CompleteMultipartUpload(*zenkocloudserver.CompleteMultipartUploadInput) (*zenkocloudserver.CompleteMultipartUploadOutput, error)
	CompleteMultipartUploadWithContext(aws.Context, *zenkocloudserver.CompleteMultipartUploadInput, ...request.Option) (*zenkocloudserver.CompleteMultipartUploadOutput, error)
	CompleteMultipartUploadRequest(*zenkocloudserver.CompleteMultipartUploadInput) (*request.Request, *zenkocloudserver.CompleteMultipartUploadOutput)

	CopyObject(*zenkocloudserver.CopyObjectInput) (*zenkocloudserver.CopyObjectOutput, error)
	CopyObjectWithContext(aws.Context, *zenkocloudserver.CopyObjectInput, ...request.Option) (*zenkocloudserver.CopyObjectOutput, error)
	CopyObjectRequest(*zenkocloudserver.CopyObjectInput) (*request.Request, *zenkocloudserver.CopyObjectOutput)

	CreateBucket(*zenkocloudserver.CreateBucketInput) (*zenkocloudserver.CreateBucketOutput, error)
	CreateBucketWithContext(aws.Context, *zenkocloudserver.CreateBucketInput, ...request.Option) (*zenkocloudserver.CreateBucketOutput, error)
	CreateBucketRequest(*zenkocloudserver.CreateBucketInput) (*request.Request, *zenkocloudserver.CreateBucketOutput)

	CreateMultipartUpload(*zenkocloudserver.CreateMultipartUploadInput) (*zenkocloudserver.CreateMultipartUploadOutput, error)
	CreateMultipartUploadWithContext(aws.Context, *zenkocloudserver.CreateMultipartUploadInput, ...request.Option) (*zenkocloudserver.CreateMultipartUploadOutput, error)
	CreateMultipartUploadRequest(*zenkocloudserver.CreateMultipartUploadInput) (*request.Request, *zenkocloudserver.CreateMultipartUploadOutput)

	DeleteBucket(*zenkocloudserver.DeleteBucketInput) (*zenkocloudserver.DeleteBucketOutput, error)
	DeleteBucketWithContext(aws.Context, *zenkocloudserver.DeleteBucketInput, ...request.Option) (*zenkocloudserver.DeleteBucketOutput, error)
	DeleteBucketRequest(*zenkocloudserver.DeleteBucketInput) (*request.Request, *zenkocloudserver.DeleteBucketOutput)

	DeleteBucketAnalyticsConfiguration(*zenkocloudserver.DeleteBucketAnalyticsConfigurationInput) (*zenkocloudserver.DeleteBucketAnalyticsConfigurationOutput, error)
	DeleteBucketAnalyticsConfigurationWithContext(aws.Context, *zenkocloudserver.DeleteBucketAnalyticsConfigurationInput, ...request.Option) (*zenkocloudserver.DeleteBucketAnalyticsConfigurationOutput, error)
	DeleteBucketAnalyticsConfigurationRequest(*zenkocloudserver.DeleteBucketAnalyticsConfigurationInput) (*request.Request, *zenkocloudserver.DeleteBucketAnalyticsConfigurationOutput)

	DeleteBucketCors(*zenkocloudserver.DeleteBucketCorsInput) (*zenkocloudserver.DeleteBucketCorsOutput, error)
	DeleteBucketCorsWithContext(aws.Context, *zenkocloudserver.DeleteBucketCorsInput, ...request.Option) (*zenkocloudserver.DeleteBucketCorsOutput, error)
	DeleteBucketCorsRequest(*zenkocloudserver.DeleteBucketCorsInput) (*request.Request, *zenkocloudserver.DeleteBucketCorsOutput)

	DeleteBucketEncryption(*zenkocloudserver.DeleteBucketEncryptionInput) (*zenkocloudserver.DeleteBucketEncryptionOutput, error)
	DeleteBucketEncryptionWithContext(aws.Context, *zenkocloudserver.DeleteBucketEncryptionInput, ...request.Option) (*zenkocloudserver.DeleteBucketEncryptionOutput, error)
	DeleteBucketEncryptionRequest(*zenkocloudserver.DeleteBucketEncryptionInput) (*request.Request, *zenkocloudserver.DeleteBucketEncryptionOutput)

	DeleteBucketInventoryConfiguration(*zenkocloudserver.DeleteBucketInventoryConfigurationInput) (*zenkocloudserver.DeleteBucketInventoryConfigurationOutput, error)
	DeleteBucketInventoryConfigurationWithContext(aws.Context, *zenkocloudserver.DeleteBucketInventoryConfigurationInput, ...request.Option) (*zenkocloudserver.DeleteBucketInventoryConfigurationOutput, error)
	DeleteBucketInventoryConfigurationRequest(*zenkocloudserver.DeleteBucketInventoryConfigurationInput) (*request.Request, *zenkocloudserver.DeleteBucketInventoryConfigurationOutput)

	DeleteBucketLifecycle(*zenkocloudserver.DeleteBucketLifecycleInput) (*zenkocloudserver.DeleteBucketLifecycleOutput, error)
	DeleteBucketLifecycleWithContext(aws.Context, *zenkocloudserver.DeleteBucketLifecycleInput, ...request.Option) (*zenkocloudserver.DeleteBucketLifecycleOutput, error)
	DeleteBucketLifecycleRequest(*zenkocloudserver.DeleteBucketLifecycleInput) (*request.Request, *zenkocloudserver.DeleteBucketLifecycleOutput)

	DeleteBucketMetricsConfiguration(*zenkocloudserver.DeleteBucketMetricsConfigurationInput) (*zenkocloudserver.DeleteBucketMetricsConfigurationOutput, error)
	DeleteBucketMetricsConfigurationWithContext(aws.Context, *zenkocloudserver.DeleteBucketMetricsConfigurationInput, ...request.Option) (*zenkocloudserver.DeleteBucketMetricsConfigurationOutput, error)
	DeleteBucketMetricsConfigurationRequest(*zenkocloudserver.DeleteBucketMetricsConfigurationInput) (*request.Request, *zenkocloudserver.DeleteBucketMetricsConfigurationOutput)

	DeleteBucketPolicy(*zenkocloudserver.DeleteBucketPolicyInput) (*zenkocloudserver.DeleteBucketPolicyOutput, error)
	DeleteBucketPolicyWithContext(aws.Context, *zenkocloudserver.DeleteBucketPolicyInput, ...request.Option) (*zenkocloudserver.DeleteBucketPolicyOutput, error)
	DeleteBucketPolicyRequest(*zenkocloudserver.DeleteBucketPolicyInput) (*request.Request, *zenkocloudserver.DeleteBucketPolicyOutput)

	DeleteBucketReplication(*zenkocloudserver.DeleteBucketReplicationInput) (*zenkocloudserver.DeleteBucketReplicationOutput, error)
	DeleteBucketReplicationWithContext(aws.Context, *zenkocloudserver.DeleteBucketReplicationInput, ...request.Option) (*zenkocloudserver.DeleteBucketReplicationOutput, error)
	DeleteBucketReplicationRequest(*zenkocloudserver.DeleteBucketReplicationInput) (*request.Request, *zenkocloudserver.DeleteBucketReplicationOutput)

	DeleteBucketTagging(*zenkocloudserver.DeleteBucketTaggingInput) (*zenkocloudserver.DeleteBucketTaggingOutput, error)
	DeleteBucketTaggingWithContext(aws.Context, *zenkocloudserver.DeleteBucketTaggingInput, ...request.Option) (*zenkocloudserver.DeleteBucketTaggingOutput, error)
	DeleteBucketTaggingRequest(*zenkocloudserver.DeleteBucketTaggingInput) (*request.Request, *zenkocloudserver.DeleteBucketTaggingOutput)

	DeleteBucketWebsite(*zenkocloudserver.DeleteBucketWebsiteInput) (*zenkocloudserver.DeleteBucketWebsiteOutput, error)
	DeleteBucketWebsiteWithContext(aws.Context, *zenkocloudserver.DeleteBucketWebsiteInput, ...request.Option) (*zenkocloudserver.DeleteBucketWebsiteOutput, error)
	DeleteBucketWebsiteRequest(*zenkocloudserver.DeleteBucketWebsiteInput) (*request.Request, *zenkocloudserver.DeleteBucketWebsiteOutput)

	DeleteObject(*zenkocloudserver.DeleteObjectInput) (*zenkocloudserver.DeleteObjectOutput, error)
	DeleteObjectWithContext(aws.Context, *zenkocloudserver.DeleteObjectInput, ...request.Option) (*zenkocloudserver.DeleteObjectOutput, error)
	DeleteObjectRequest(*zenkocloudserver.DeleteObjectInput) (*request.Request, *zenkocloudserver.DeleteObjectOutput)

	DeleteObjectTagging(*zenkocloudserver.DeleteObjectTaggingInput) (*zenkocloudserver.DeleteObjectTaggingOutput, error)
	DeleteObjectTaggingWithContext(aws.Context, *zenkocloudserver.DeleteObjectTaggingInput, ...request.Option) (*zenkocloudserver.DeleteObjectTaggingOutput, error)
	DeleteObjectTaggingRequest(*zenkocloudserver.DeleteObjectTaggingInput) (*request.Request, *zenkocloudserver.DeleteObjectTaggingOutput)

	DeleteObjects(*zenkocloudserver.DeleteObjectsInput) (*zenkocloudserver.DeleteObjectsOutput, error)
	DeleteObjectsWithContext(aws.Context, *zenkocloudserver.DeleteObjectsInput, ...request.Option) (*zenkocloudserver.DeleteObjectsOutput, error)
	DeleteObjectsRequest(*zenkocloudserver.DeleteObjectsInput) (*request.Request, *zenkocloudserver.DeleteObjectsOutput)

	GetBucketAccelerateConfiguration(*zenkocloudserver.GetBucketAccelerateConfigurationInput) (*zenkocloudserver.GetBucketAccelerateConfigurationOutput, error)
	GetBucketAccelerateConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketAccelerateConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketAccelerateConfigurationOutput, error)
	GetBucketAccelerateConfigurationRequest(*zenkocloudserver.GetBucketAccelerateConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketAccelerateConfigurationOutput)

	GetBucketAcl(*zenkocloudserver.GetBucketAclInput) (*zenkocloudserver.GetBucketAclOutput, error)
	GetBucketAclWithContext(aws.Context, *zenkocloudserver.GetBucketAclInput, ...request.Option) (*zenkocloudserver.GetBucketAclOutput, error)
	GetBucketAclRequest(*zenkocloudserver.GetBucketAclInput) (*request.Request, *zenkocloudserver.GetBucketAclOutput)

	GetBucketAnalyticsConfiguration(*zenkocloudserver.GetBucketAnalyticsConfigurationInput) (*zenkocloudserver.GetBucketAnalyticsConfigurationOutput, error)
	GetBucketAnalyticsConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketAnalyticsConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketAnalyticsConfigurationOutput, error)
	GetBucketAnalyticsConfigurationRequest(*zenkocloudserver.GetBucketAnalyticsConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketAnalyticsConfigurationOutput)

	GetBucketCors(*zenkocloudserver.GetBucketCorsInput) (*zenkocloudserver.GetBucketCorsOutput, error)
	GetBucketCorsWithContext(aws.Context, *zenkocloudserver.GetBucketCorsInput, ...request.Option) (*zenkocloudserver.GetBucketCorsOutput, error)
	GetBucketCorsRequest(*zenkocloudserver.GetBucketCorsInput) (*request.Request, *zenkocloudserver.GetBucketCorsOutput)

	GetBucketEncryption(*zenkocloudserver.GetBucketEncryptionInput) (*zenkocloudserver.GetBucketEncryptionOutput, error)
	GetBucketEncryptionWithContext(aws.Context, *zenkocloudserver.GetBucketEncryptionInput, ...request.Option) (*zenkocloudserver.GetBucketEncryptionOutput, error)
	GetBucketEncryptionRequest(*zenkocloudserver.GetBucketEncryptionInput) (*request.Request, *zenkocloudserver.GetBucketEncryptionOutput)

	GetBucketInventoryConfiguration(*zenkocloudserver.GetBucketInventoryConfigurationInput) (*zenkocloudserver.GetBucketInventoryConfigurationOutput, error)
	GetBucketInventoryConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketInventoryConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketInventoryConfigurationOutput, error)
	GetBucketInventoryConfigurationRequest(*zenkocloudserver.GetBucketInventoryConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketInventoryConfigurationOutput)

	GetBucketLifecycle(*zenkocloudserver.GetBucketLifecycleInput) (*zenkocloudserver.GetBucketLifecycleOutput, error)
	GetBucketLifecycleWithContext(aws.Context, *zenkocloudserver.GetBucketLifecycleInput, ...request.Option) (*zenkocloudserver.GetBucketLifecycleOutput, error)
	GetBucketLifecycleRequest(*zenkocloudserver.GetBucketLifecycleInput) (*request.Request, *zenkocloudserver.GetBucketLifecycleOutput)

	GetBucketLifecycleConfiguration(*zenkocloudserver.GetBucketLifecycleConfigurationInput) (*zenkocloudserver.GetBucketLifecycleConfigurationOutput, error)
	GetBucketLifecycleConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketLifecycleConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketLifecycleConfigurationOutput, error)
	GetBucketLifecycleConfigurationRequest(*zenkocloudserver.GetBucketLifecycleConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketLifecycleConfigurationOutput)

	GetBucketLocation(*zenkocloudserver.GetBucketLocationInput) (*zenkocloudserver.GetBucketLocationOutput, error)
	GetBucketLocationWithContext(aws.Context, *zenkocloudserver.GetBucketLocationInput, ...request.Option) (*zenkocloudserver.GetBucketLocationOutput, error)
	GetBucketLocationRequest(*zenkocloudserver.GetBucketLocationInput) (*request.Request, *zenkocloudserver.GetBucketLocationOutput)

	GetBucketLogging(*zenkocloudserver.GetBucketLoggingInput) (*zenkocloudserver.GetBucketLoggingOutput, error)
	GetBucketLoggingWithContext(aws.Context, *zenkocloudserver.GetBucketLoggingInput, ...request.Option) (*zenkocloudserver.GetBucketLoggingOutput, error)
	GetBucketLoggingRequest(*zenkocloudserver.GetBucketLoggingInput) (*request.Request, *zenkocloudserver.GetBucketLoggingOutput)

	GetBucketMetricsConfiguration(*zenkocloudserver.GetBucketMetricsConfigurationInput) (*zenkocloudserver.GetBucketMetricsConfigurationOutput, error)
	GetBucketMetricsConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketMetricsConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketMetricsConfigurationOutput, error)
	GetBucketMetricsConfigurationRequest(*zenkocloudserver.GetBucketMetricsConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketMetricsConfigurationOutput)

	GetBucketNotification(*zenkocloudserver.GetBucketNotificationInput) (*zenkocloudserver.GetBucketNotificationOutput, error)
	GetBucketNotificationWithContext(aws.Context, *zenkocloudserver.GetBucketNotificationInput, ...request.Option) (*zenkocloudserver.GetBucketNotificationOutput, error)
	GetBucketNotificationRequest(*zenkocloudserver.GetBucketNotificationInput) (*request.Request, *zenkocloudserver.GetBucketNotificationOutput)

	GetBucketNotificationConfiguration(*zenkocloudserver.GetBucketNotificationConfigurationInput) (*zenkocloudserver.GetBucketNotificationConfigurationOutput, error)
	GetBucketNotificationConfigurationWithContext(aws.Context, *zenkocloudserver.GetBucketNotificationConfigurationInput, ...request.Option) (*zenkocloudserver.GetBucketNotificationConfigurationOutput, error)
	GetBucketNotificationConfigurationRequest(*zenkocloudserver.GetBucketNotificationConfigurationInput) (*request.Request, *zenkocloudserver.GetBucketNotificationConfigurationOutput)

	GetBucketPolicy(*zenkocloudserver.GetBucketPolicyInput) (*zenkocloudserver.GetBucketPolicyOutput, error)
	GetBucketPolicyWithContext(aws.Context, *zenkocloudserver.GetBucketPolicyInput, ...request.Option) (*zenkocloudserver.GetBucketPolicyOutput, error)
	GetBucketPolicyRequest(*zenkocloudserver.GetBucketPolicyInput) (*request.Request, *zenkocloudserver.GetBucketPolicyOutput)

	GetBucketReplication(*zenkocloudserver.GetBucketReplicationInput) (*zenkocloudserver.GetBucketReplicationOutput, error)
	GetBucketReplicationWithContext(aws.Context, *zenkocloudserver.GetBucketReplicationInput, ...request.Option) (*zenkocloudserver.GetBucketReplicationOutput, error)
	GetBucketReplicationRequest(*zenkocloudserver.GetBucketReplicationInput) (*request.Request, *zenkocloudserver.GetBucketReplicationOutput)

	GetBucketRequestPayment(*zenkocloudserver.GetBucketRequestPaymentInput) (*zenkocloudserver.GetBucketRequestPaymentOutput, error)
	GetBucketRequestPaymentWithContext(aws.Context, *zenkocloudserver.GetBucketRequestPaymentInput, ...request.Option) (*zenkocloudserver.GetBucketRequestPaymentOutput, error)
	GetBucketRequestPaymentRequest(*zenkocloudserver.GetBucketRequestPaymentInput) (*request.Request, *zenkocloudserver.GetBucketRequestPaymentOutput)

	GetBucketTagging(*zenkocloudserver.GetBucketTaggingInput) (*zenkocloudserver.GetBucketTaggingOutput, error)
	GetBucketTaggingWithContext(aws.Context, *zenkocloudserver.GetBucketTaggingInput, ...request.Option) (*zenkocloudserver.GetBucketTaggingOutput, error)
	GetBucketTaggingRequest(*zenkocloudserver.GetBucketTaggingInput) (*request.Request, *zenkocloudserver.GetBucketTaggingOutput)

	GetBucketVersioning(*zenkocloudserver.GetBucketVersioningInput) (*zenkocloudserver.GetBucketVersioningOutput, error)
	GetBucketVersioningWithContext(aws.Context, *zenkocloudserver.GetBucketVersioningInput, ...request.Option) (*zenkocloudserver.GetBucketVersioningOutput, error)
	GetBucketVersioningRequest(*zenkocloudserver.GetBucketVersioningInput) (*request.Request, *zenkocloudserver.GetBucketVersioningOutput)

	GetBucketWebsite(*zenkocloudserver.GetBucketWebsiteInput) (*zenkocloudserver.GetBucketWebsiteOutput, error)
	GetBucketWebsiteWithContext(aws.Context, *zenkocloudserver.GetBucketWebsiteInput, ...request.Option) (*zenkocloudserver.GetBucketWebsiteOutput, error)
	GetBucketWebsiteRequest(*zenkocloudserver.GetBucketWebsiteInput) (*request.Request, *zenkocloudserver.GetBucketWebsiteOutput)

	GetObject(*zenkocloudserver.GetObjectInput) (*zenkocloudserver.GetObjectOutput, error)
	GetObjectWithContext(aws.Context, *zenkocloudserver.GetObjectInput, ...request.Option) (*zenkocloudserver.GetObjectOutput, error)
	GetObjectRequest(*zenkocloudserver.GetObjectInput) (*request.Request, *zenkocloudserver.GetObjectOutput)

	GetObjectAcl(*zenkocloudserver.GetObjectAclInput) (*zenkocloudserver.GetObjectAclOutput, error)
	GetObjectAclWithContext(aws.Context, *zenkocloudserver.GetObjectAclInput, ...request.Option) (*zenkocloudserver.GetObjectAclOutput, error)
	GetObjectAclRequest(*zenkocloudserver.GetObjectAclInput) (*request.Request, *zenkocloudserver.GetObjectAclOutput)

	GetObjectTagging(*zenkocloudserver.GetObjectTaggingInput) (*zenkocloudserver.GetObjectTaggingOutput, error)
	GetObjectTaggingWithContext(aws.Context, *zenkocloudserver.GetObjectTaggingInput, ...request.Option) (*zenkocloudserver.GetObjectTaggingOutput, error)
	GetObjectTaggingRequest(*zenkocloudserver.GetObjectTaggingInput) (*request.Request, *zenkocloudserver.GetObjectTaggingOutput)

	GetObjectTorrent(*zenkocloudserver.GetObjectTorrentInput) (*zenkocloudserver.GetObjectTorrentOutput, error)
	GetObjectTorrentWithContext(aws.Context, *zenkocloudserver.GetObjectTorrentInput, ...request.Option) (*zenkocloudserver.GetObjectTorrentOutput, error)
	GetObjectTorrentRequest(*zenkocloudserver.GetObjectTorrentInput) (*request.Request, *zenkocloudserver.GetObjectTorrentOutput)

	HeadBucket(*zenkocloudserver.HeadBucketInput) (*zenkocloudserver.HeadBucketOutput, error)
	HeadBucketWithContext(aws.Context, *zenkocloudserver.HeadBucketInput, ...request.Option) (*zenkocloudserver.HeadBucketOutput, error)
	HeadBucketRequest(*zenkocloudserver.HeadBucketInput) (*request.Request, *zenkocloudserver.HeadBucketOutput)

	HeadObject(*zenkocloudserver.HeadObjectInput) (*zenkocloudserver.HeadObjectOutput, error)
	HeadObjectWithContext(aws.Context, *zenkocloudserver.HeadObjectInput, ...request.Option) (*zenkocloudserver.HeadObjectOutput, error)
	HeadObjectRequest(*zenkocloudserver.HeadObjectInput) (*request.Request, *zenkocloudserver.HeadObjectOutput)

	ListBucketAnalyticsConfigurations(*zenkocloudserver.ListBucketAnalyticsConfigurationsInput) (*zenkocloudserver.ListBucketAnalyticsConfigurationsOutput, error)
	ListBucketAnalyticsConfigurationsWithContext(aws.Context, *zenkocloudserver.ListBucketAnalyticsConfigurationsInput, ...request.Option) (*zenkocloudserver.ListBucketAnalyticsConfigurationsOutput, error)
	ListBucketAnalyticsConfigurationsRequest(*zenkocloudserver.ListBucketAnalyticsConfigurationsInput) (*request.Request, *zenkocloudserver.ListBucketAnalyticsConfigurationsOutput)

	ListBucketInventoryConfigurations(*zenkocloudserver.ListBucketInventoryConfigurationsInput) (*zenkocloudserver.ListBucketInventoryConfigurationsOutput, error)
	ListBucketInventoryConfigurationsWithContext(aws.Context, *zenkocloudserver.ListBucketInventoryConfigurationsInput, ...request.Option) (*zenkocloudserver.ListBucketInventoryConfigurationsOutput, error)
	ListBucketInventoryConfigurationsRequest(*zenkocloudserver.ListBucketInventoryConfigurationsInput) (*request.Request, *zenkocloudserver.ListBucketInventoryConfigurationsOutput)

	ListBucketMetricsConfigurations(*zenkocloudserver.ListBucketMetricsConfigurationsInput) (*zenkocloudserver.ListBucketMetricsConfigurationsOutput, error)
	ListBucketMetricsConfigurationsWithContext(aws.Context, *zenkocloudserver.ListBucketMetricsConfigurationsInput, ...request.Option) (*zenkocloudserver.ListBucketMetricsConfigurationsOutput, error)
	ListBucketMetricsConfigurationsRequest(*zenkocloudserver.ListBucketMetricsConfigurationsInput) (*request.Request, *zenkocloudserver.ListBucketMetricsConfigurationsOutput)

	ListBuckets(*zenkocloudserver.ListBucketsInput) (*zenkocloudserver.ListBucketsOutput, error)
	ListBucketsWithContext(aws.Context, *zenkocloudserver.ListBucketsInput, ...request.Option) (*zenkocloudserver.ListBucketsOutput, error)
	ListBucketsRequest(*zenkocloudserver.ListBucketsInput) (*request.Request, *zenkocloudserver.ListBucketsOutput)

	ListMultipartUploads(*zenkocloudserver.ListMultipartUploadsInput) (*zenkocloudserver.ListMultipartUploadsOutput, error)
	ListMultipartUploadsWithContext(aws.Context, *zenkocloudserver.ListMultipartUploadsInput, ...request.Option) (*zenkocloudserver.ListMultipartUploadsOutput, error)
	ListMultipartUploadsRequest(*zenkocloudserver.ListMultipartUploadsInput) (*request.Request, *zenkocloudserver.ListMultipartUploadsOutput)

	ListMultipartUploadsPages(*zenkocloudserver.ListMultipartUploadsInput, func(*zenkocloudserver.ListMultipartUploadsOutput, bool) bool) error
	ListMultipartUploadsPagesWithContext(aws.Context, *zenkocloudserver.ListMultipartUploadsInput, func(*zenkocloudserver.ListMultipartUploadsOutput, bool) bool, ...request.Option) error

	ListObjectVersions(*zenkocloudserver.ListObjectVersionsInput) (*zenkocloudserver.ListObjectVersionsOutput, error)
	ListObjectVersionsWithContext(aws.Context, *zenkocloudserver.ListObjectVersionsInput, ...request.Option) (*zenkocloudserver.ListObjectVersionsOutput, error)
	ListObjectVersionsRequest(*zenkocloudserver.ListObjectVersionsInput) (*request.Request, *zenkocloudserver.ListObjectVersionsOutput)

	ListObjectVersionsPages(*zenkocloudserver.ListObjectVersionsInput, func(*zenkocloudserver.ListObjectVersionsOutput, bool) bool) error
	ListObjectVersionsPagesWithContext(aws.Context, *zenkocloudserver.ListObjectVersionsInput, func(*zenkocloudserver.ListObjectVersionsOutput, bool) bool, ...request.Option) error

	ListObjects(*zenkocloudserver.ListObjectsInput) (*zenkocloudserver.ListObjectsOutput, error)
	ListObjectsWithContext(aws.Context, *zenkocloudserver.ListObjectsInput, ...request.Option) (*zenkocloudserver.ListObjectsOutput, error)
	ListObjectsRequest(*zenkocloudserver.ListObjectsInput) (*request.Request, *zenkocloudserver.ListObjectsOutput)

	ListObjectsPages(*zenkocloudserver.ListObjectsInput, func(*zenkocloudserver.ListObjectsOutput, bool) bool) error
	ListObjectsPagesWithContext(aws.Context, *zenkocloudserver.ListObjectsInput, func(*zenkocloudserver.ListObjectsOutput, bool) bool, ...request.Option) error

	ListObjectsV2(*zenkocloudserver.ListObjectsV2Input) (*zenkocloudserver.ListObjectsV2Output, error)
	ListObjectsV2WithContext(aws.Context, *zenkocloudserver.ListObjectsV2Input, ...request.Option) (*zenkocloudserver.ListObjectsV2Output, error)
	ListObjectsV2Request(*zenkocloudserver.ListObjectsV2Input) (*request.Request, *zenkocloudserver.ListObjectsV2Output)

	ListObjectsV2Pages(*zenkocloudserver.ListObjectsV2Input, func(*zenkocloudserver.ListObjectsV2Output, bool) bool) error
	ListObjectsV2PagesWithContext(aws.Context, *zenkocloudserver.ListObjectsV2Input, func(*zenkocloudserver.ListObjectsV2Output, bool) bool, ...request.Option) error

	ListParts(*zenkocloudserver.ListPartsInput) (*zenkocloudserver.ListPartsOutput, error)
	ListPartsWithContext(aws.Context, *zenkocloudserver.ListPartsInput, ...request.Option) (*zenkocloudserver.ListPartsOutput, error)
	ListPartsRequest(*zenkocloudserver.ListPartsInput) (*request.Request, *zenkocloudserver.ListPartsOutput)

	ListPartsPages(*zenkocloudserver.ListPartsInput, func(*zenkocloudserver.ListPartsOutput, bool) bool) error
	ListPartsPagesWithContext(aws.Context, *zenkocloudserver.ListPartsInput, func(*zenkocloudserver.ListPartsOutput, bool) bool, ...request.Option) error

	PutBucketAccelerateConfiguration(*zenkocloudserver.PutBucketAccelerateConfigurationInput) (*zenkocloudserver.PutBucketAccelerateConfigurationOutput, error)
	PutBucketAccelerateConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketAccelerateConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketAccelerateConfigurationOutput, error)
	PutBucketAccelerateConfigurationRequest(*zenkocloudserver.PutBucketAccelerateConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketAccelerateConfigurationOutput)

	PutBucketAcl(*zenkocloudserver.PutBucketAclInput) (*zenkocloudserver.PutBucketAclOutput, error)
	PutBucketAclWithContext(aws.Context, *zenkocloudserver.PutBucketAclInput, ...request.Option) (*zenkocloudserver.PutBucketAclOutput, error)
	PutBucketAclRequest(*zenkocloudserver.PutBucketAclInput) (*request.Request, *zenkocloudserver.PutBucketAclOutput)

	PutBucketAnalyticsConfiguration(*zenkocloudserver.PutBucketAnalyticsConfigurationInput) (*zenkocloudserver.PutBucketAnalyticsConfigurationOutput, error)
	PutBucketAnalyticsConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketAnalyticsConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketAnalyticsConfigurationOutput, error)
	PutBucketAnalyticsConfigurationRequest(*zenkocloudserver.PutBucketAnalyticsConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketAnalyticsConfigurationOutput)

	PutBucketCors(*zenkocloudserver.PutBucketCorsInput) (*zenkocloudserver.PutBucketCorsOutput, error)
	PutBucketCorsWithContext(aws.Context, *zenkocloudserver.PutBucketCorsInput, ...request.Option) (*zenkocloudserver.PutBucketCorsOutput, error)
	PutBucketCorsRequest(*zenkocloudserver.PutBucketCorsInput) (*request.Request, *zenkocloudserver.PutBucketCorsOutput)

	PutBucketEncryption(*zenkocloudserver.PutBucketEncryptionInput) (*zenkocloudserver.PutBucketEncryptionOutput, error)
	PutBucketEncryptionWithContext(aws.Context, *zenkocloudserver.PutBucketEncryptionInput, ...request.Option) (*zenkocloudserver.PutBucketEncryptionOutput, error)
	PutBucketEncryptionRequest(*zenkocloudserver.PutBucketEncryptionInput) (*request.Request, *zenkocloudserver.PutBucketEncryptionOutput)

	PutBucketInventoryConfiguration(*zenkocloudserver.PutBucketInventoryConfigurationInput) (*zenkocloudserver.PutBucketInventoryConfigurationOutput, error)
	PutBucketInventoryConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketInventoryConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketInventoryConfigurationOutput, error)
	PutBucketInventoryConfigurationRequest(*zenkocloudserver.PutBucketInventoryConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketInventoryConfigurationOutput)

	PutBucketLifecycle(*zenkocloudserver.PutBucketLifecycleInput) (*zenkocloudserver.PutBucketLifecycleOutput, error)
	PutBucketLifecycleWithContext(aws.Context, *zenkocloudserver.PutBucketLifecycleInput, ...request.Option) (*zenkocloudserver.PutBucketLifecycleOutput, error)
	PutBucketLifecycleRequest(*zenkocloudserver.PutBucketLifecycleInput) (*request.Request, *zenkocloudserver.PutBucketLifecycleOutput)

	PutBucketLifecycleConfiguration(*zenkocloudserver.PutBucketLifecycleConfigurationInput) (*zenkocloudserver.PutBucketLifecycleConfigurationOutput, error)
	PutBucketLifecycleConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketLifecycleConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketLifecycleConfigurationOutput, error)
	PutBucketLifecycleConfigurationRequest(*zenkocloudserver.PutBucketLifecycleConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketLifecycleConfigurationOutput)

	PutBucketLogging(*zenkocloudserver.PutBucketLoggingInput) (*zenkocloudserver.PutBucketLoggingOutput, error)
	PutBucketLoggingWithContext(aws.Context, *zenkocloudserver.PutBucketLoggingInput, ...request.Option) (*zenkocloudserver.PutBucketLoggingOutput, error)
	PutBucketLoggingRequest(*zenkocloudserver.PutBucketLoggingInput) (*request.Request, *zenkocloudserver.PutBucketLoggingOutput)

	PutBucketMetricsConfiguration(*zenkocloudserver.PutBucketMetricsConfigurationInput) (*zenkocloudserver.PutBucketMetricsConfigurationOutput, error)
	PutBucketMetricsConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketMetricsConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketMetricsConfigurationOutput, error)
	PutBucketMetricsConfigurationRequest(*zenkocloudserver.PutBucketMetricsConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketMetricsConfigurationOutput)

	PutBucketNotification(*zenkocloudserver.PutBucketNotificationInput) (*zenkocloudserver.PutBucketNotificationOutput, error)
	PutBucketNotificationWithContext(aws.Context, *zenkocloudserver.PutBucketNotificationInput, ...request.Option) (*zenkocloudserver.PutBucketNotificationOutput, error)
	PutBucketNotificationRequest(*zenkocloudserver.PutBucketNotificationInput) (*request.Request, *zenkocloudserver.PutBucketNotificationOutput)

	PutBucketNotificationConfiguration(*zenkocloudserver.PutBucketNotificationConfigurationInput) (*zenkocloudserver.PutBucketNotificationConfigurationOutput, error)
	PutBucketNotificationConfigurationWithContext(aws.Context, *zenkocloudserver.PutBucketNotificationConfigurationInput, ...request.Option) (*zenkocloudserver.PutBucketNotificationConfigurationOutput, error)
	PutBucketNotificationConfigurationRequest(*zenkocloudserver.PutBucketNotificationConfigurationInput) (*request.Request, *zenkocloudserver.PutBucketNotificationConfigurationOutput)

	PutBucketPolicy(*zenkocloudserver.PutBucketPolicyInput) (*zenkocloudserver.PutBucketPolicyOutput, error)
	PutBucketPolicyWithContext(aws.Context, *zenkocloudserver.PutBucketPolicyInput, ...request.Option) (*zenkocloudserver.PutBucketPolicyOutput, error)
	PutBucketPolicyRequest(*zenkocloudserver.PutBucketPolicyInput) (*request.Request, *zenkocloudserver.PutBucketPolicyOutput)

	PutBucketReplication(*zenkocloudserver.PutBucketReplicationInput) (*zenkocloudserver.PutBucketReplicationOutput, error)
	PutBucketReplicationWithContext(aws.Context, *zenkocloudserver.PutBucketReplicationInput, ...request.Option) (*zenkocloudserver.PutBucketReplicationOutput, error)
	PutBucketReplicationRequest(*zenkocloudserver.PutBucketReplicationInput) (*request.Request, *zenkocloudserver.PutBucketReplicationOutput)

	PutBucketRequestPayment(*zenkocloudserver.PutBucketRequestPaymentInput) (*zenkocloudserver.PutBucketRequestPaymentOutput, error)
	PutBucketRequestPaymentWithContext(aws.Context, *zenkocloudserver.PutBucketRequestPaymentInput, ...request.Option) (*zenkocloudserver.PutBucketRequestPaymentOutput, error)
	PutBucketRequestPaymentRequest(*zenkocloudserver.PutBucketRequestPaymentInput) (*request.Request, *zenkocloudserver.PutBucketRequestPaymentOutput)

	PutBucketTagging(*zenkocloudserver.PutBucketTaggingInput) (*zenkocloudserver.PutBucketTaggingOutput, error)
	PutBucketTaggingWithContext(aws.Context, *zenkocloudserver.PutBucketTaggingInput, ...request.Option) (*zenkocloudserver.PutBucketTaggingOutput, error)
	PutBucketTaggingRequest(*zenkocloudserver.PutBucketTaggingInput) (*request.Request, *zenkocloudserver.PutBucketTaggingOutput)

	PutBucketVersioning(*zenkocloudserver.PutBucketVersioningInput) (*zenkocloudserver.PutBucketVersioningOutput, error)
	PutBucketVersioningWithContext(aws.Context, *zenkocloudserver.PutBucketVersioningInput, ...request.Option) (*zenkocloudserver.PutBucketVersioningOutput, error)
	PutBucketVersioningRequest(*zenkocloudserver.PutBucketVersioningInput) (*request.Request, *zenkocloudserver.PutBucketVersioningOutput)

	PutBucketWebsite(*zenkocloudserver.PutBucketWebsiteInput) (*zenkocloudserver.PutBucketWebsiteOutput, error)
	PutBucketWebsiteWithContext(aws.Context, *zenkocloudserver.PutBucketWebsiteInput, ...request.Option) (*zenkocloudserver.PutBucketWebsiteOutput, error)
	PutBucketWebsiteRequest(*zenkocloudserver.PutBucketWebsiteInput) (*request.Request, *zenkocloudserver.PutBucketWebsiteOutput)

	PutObject(*zenkocloudserver.PutObjectInput) (*zenkocloudserver.PutObjectOutput, error)
	PutObjectWithContext(aws.Context, *zenkocloudserver.PutObjectInput, ...request.Option) (*zenkocloudserver.PutObjectOutput, error)
	PutObjectRequest(*zenkocloudserver.PutObjectInput) (*request.Request, *zenkocloudserver.PutObjectOutput)

	PutObjectAcl(*zenkocloudserver.PutObjectAclInput) (*zenkocloudserver.PutObjectAclOutput, error)
	PutObjectAclWithContext(aws.Context, *zenkocloudserver.PutObjectAclInput, ...request.Option) (*zenkocloudserver.PutObjectAclOutput, error)
	PutObjectAclRequest(*zenkocloudserver.PutObjectAclInput) (*request.Request, *zenkocloudserver.PutObjectAclOutput)

	PutObjectTagging(*zenkocloudserver.PutObjectTaggingInput) (*zenkocloudserver.PutObjectTaggingOutput, error)
	PutObjectTaggingWithContext(aws.Context, *zenkocloudserver.PutObjectTaggingInput, ...request.Option) (*zenkocloudserver.PutObjectTaggingOutput, error)
	PutObjectTaggingRequest(*zenkocloudserver.PutObjectTaggingInput) (*request.Request, *zenkocloudserver.PutObjectTaggingOutput)

	RestoreObject(*zenkocloudserver.RestoreObjectInput) (*zenkocloudserver.RestoreObjectOutput, error)
	RestoreObjectWithContext(aws.Context, *zenkocloudserver.RestoreObjectInput, ...request.Option) (*zenkocloudserver.RestoreObjectOutput, error)
	RestoreObjectRequest(*zenkocloudserver.RestoreObjectInput) (*request.Request, *zenkocloudserver.RestoreObjectOutput)

	SelectObjectContent(*zenkocloudserver.SelectObjectContentInput) (*zenkocloudserver.SelectObjectContentOutput, error)
	SelectObjectContentWithContext(aws.Context, *zenkocloudserver.SelectObjectContentInput, ...request.Option) (*zenkocloudserver.SelectObjectContentOutput, error)
	SelectObjectContentRequest(*zenkocloudserver.SelectObjectContentInput) (*request.Request, *zenkocloudserver.SelectObjectContentOutput)

	UploadPart(*zenkocloudserver.UploadPartInput) (*zenkocloudserver.UploadPartOutput, error)
	UploadPartWithContext(aws.Context, *zenkocloudserver.UploadPartInput, ...request.Option) (*zenkocloudserver.UploadPartOutput, error)
	UploadPartRequest(*zenkocloudserver.UploadPartInput) (*request.Request, *zenkocloudserver.UploadPartOutput)

	UploadPartCopy(*zenkocloudserver.UploadPartCopyInput) (*zenkocloudserver.UploadPartCopyOutput, error)
	UploadPartCopyWithContext(aws.Context, *zenkocloudserver.UploadPartCopyInput, ...request.Option) (*zenkocloudserver.UploadPartCopyOutput, error)
	UploadPartCopyRequest(*zenkocloudserver.UploadPartCopyInput) (*request.Request, *zenkocloudserver.UploadPartCopyOutput)

	WaitUntilBucketExists(*zenkocloudserver.HeadBucketInput) error
	WaitUntilBucketExistsWithContext(aws.Context, *zenkocloudserver.HeadBucketInput, ...request.WaiterOption) error

	WaitUntilBucketNotExists(*zenkocloudserver.HeadBucketInput) error
	WaitUntilBucketNotExistsWithContext(aws.Context, *zenkocloudserver.HeadBucketInput, ...request.WaiterOption) error

	WaitUntilObjectExists(*zenkocloudserver.HeadObjectInput) error
	WaitUntilObjectExistsWithContext(aws.Context, *zenkocloudserver.HeadObjectInput, ...request.WaiterOption) error

	WaitUntilObjectNotExists(*zenkocloudserver.HeadObjectInput) error
	WaitUntilObjectNotExistsWithContext(aws.Context, *zenkocloudserver.HeadObjectInput, ...request.WaiterOption) error
}

var _ ZenkoCloudserverAPI = (*zenkocloudserver.ZenkoCloudserver)(nil)
